# Generated by Django 4.1.5 on 2023-05-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0002_image_alter_product_options_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
