# Generated by Django 4.1.5 on 2023-05-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0003_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='photo',
        ),
    ]
